services:
  docs:
    image: track_save_local_docs
    container_name: track_save_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./track_save:/app/track_save:z
    ports:
      - '9000:9000'
    command: /start-docs
